### PR TITLE
Fix string vs integer definitions

### PR DESCRIPTION
**Pull request by cavanaug**
So these fixes I think are correct based on all the items in the Devices Database.

In the existing schemas 
    1.  The schema for baud rate is specified as a string, but in the documentation and all the example json's the field is populated as an integer
    2. The schema for timetable device actions is specified as a string, the documentation also shows examples as a string, but in the one example "Switch with power measure|2x50A" from the Device Database it is populated as an integer.    Im assuming that the example is correct because I presume otherwise it wouldnt have worked.   But I guess the example could be wrong.   

With these updates, all examples from the DeviceDatabase pass schema validation.

### CODE REVIEW

**Comment by cavanaug** [comment]
Note:  I wasnt able to figure out how to update the Wiki docs for timetable device actions.    You will need to change the docs on that one to not use "" around the numbers and to confirm it should be an integer not a string.

**Comment by RavenSystem** [comment]
> Note: I wasnt able to figure out how to update the Wiki docs for timetable device actions. You will need to change the docs on that one to not use "" around the numbers and to confirm it should be an integer not a string.

Could you tell me exactly where is it? I am not able to find it in the Wiki.

**Comment by RavenSystem** [comment]
Many thanks!

**Comment by RavenSystem** [comment]
> > Note: I wasnt able to figure out how to update the Wiki docs for timetable device actions. You will need to change the docs on that one to not use "" around the numbers and to confirm it should be an integer not a string.
> 
> Could you tell me exactly where is it? I am not able to find it in the Wiki.

I think that I know what is happening. Device actions must be declared as string `"0"`, `"1"`... because JSON keys must be strings, but they must be used as integer when used as value into "tt" array.

**Comment by RavenSystem** [comment]
I changed description of A, changing "0" to "50" part to `0` to `50`.

**Comment by cavanaug** [comment]
You should also change it at the bottom of this ref.    https://github.com/RavenSystem/esp-homekit-devices/wiki/General-Configuration#Device-actions   as it shows "50"

**Comment by cavanaug** [comment]
> 

It would probably be a good idea to note in the docs about how the actions need to be a string when used as a key, but need to be an integer when used as a value.   I mean I understand that, but Im not sure everyone else would without the explanation.

**Comment by RavenSystem** [comment]
> You should also change it at the bottom of this ref. https://github.com/RavenSystem/esp-homekit-devices/wiki/General-Configuration#Device-actions as it shows "50"

These declarations are keys and they must be strings.

**Pull request merged**
